name: CI

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    name: Test (${{ matrix.label }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
        - label: linux
          os: ubuntu-latest
          coverage: true

        - label: macos
          os: macos-latest
          coverage: true

        - label: windows
          os: windows-latest
          coverage: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Clean Install
      run: npm ci
      shell: bash

    - name: Test
      if: '!matrix.coverage'
      run: npm run test
      shell: bash

    - name: Coverage
      if: matrix.coverage
      run: npm run coverage
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Run
      uses: ./
      with:
        repo: BurntSushi/ripgrep
        tags: 13.0.0, 12.1.1
        name: ripgrep
        main: rg --version

    - name: Upload Coverage
      if: matrix.coverage
      uses: codecov/codecov-action@v3
      with:
        directory: coverage
        flags: ${{ matrix.label }}
        token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Clean Install
      run: npm ci
      shell: bash

    - name: Check Format
      run: npm run format-check
      shell: bash

    - name: Lint
      run: npm run lint
      shell: bash
